
import type { ParticleEmitterData } from './ParticleEmitter';

export const PRESETS = {
  fire: {
    rate: 30,
    lifetime: { min: 0.3, max: 0.8 },
    speed: 50,
    angle: -Math.PI / 2,
    angleSpread: 0.3,
    color: { start: '#ff6600', end: '#ff0000' },
    size: { min: 3, max: 8 },
    sizeOverLife: 0.3,
    shape: 'circle' as const,
  },
  smoke: {
    rate: 10,
    lifetime: { min: 1, max: 3 },
    speed: 20,
    angle: -Math.PI / 2,
    angleSpread: 0.5,
    color: { start: '#888888', end: '#333333' },
    size: { min: 10, max: 20 },
    sizeOverLife: 0.5,
    shape: 'circle' as const,
  },
  explosion: {
    rate: 0,
    burst: 50,
    lifetime: { min: 0.2, max: 0.6 },
    speed: 200,
    angleSpread: Math.PI * 2,
    color: { start: '#ffffff', end: '#ff6600' },
    size: { min: 2, max: 6 },
    sizeOverLife: 0.1,
    shape: 'circle' as const,
  },
  spark: {
    rate: 5,
    lifetime: { min: 0.1, max: 0.3 },
    speed: 100,
    angleSpread: Math.PI,
    color: '#ffff00',
    size: 2,
    shape: 'point' as const,
  },
  rain: {
    rate: 100,
    lifetime: { min: 1, max: 2 },
    speed: 300,
    angle: Math.PI / 2,
    angleSpread: 0.1,
    color: '#4488ff',
    size: 2,
    sizeOverLife: 0.8,
    shape: 'point' as const,
  },
  snow: {
    rate: 20,
    lifetime: { min: 3, max: 6 },
    speed: 50,
    angle: Math.PI / 2,
    angleSpread: 0.3,
    color: '#ffffff',
    size: { min: 3, max: 8 },
    sizeOverLife: 0.9,
    shape: 'circle' as const,
  },
  magic: {
    rate: 15,
    lifetime: { min: 0.5, max: 1.5 },
    speed: 100,
    angle: -Math.PI / 2,
    angleSpread: 0.5,
    color: { start: '#00ffff', end: '#ff00ff' },
    size: { min: 2, max: 5 },
    sizeOverLife: 0.5,
    shape: 'circle' as const,
  },
} as const;

export type PresetName = keyof typeof PRESETS;
